name: pkgcheck
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: git set safe.directory
        run: git config --global --add safe.directory ${{ github.workspace }}

      - name: Run pkgcheck
        uses: pkgcore/pkgcheck-action@v1
        with:
          args: --exit warning -k ,-NonsolvableDepsInStable,-NonsolvableDepsInDev,-PotentialStable --commits HEAD^..${{ github.sha }}
