name: pkgcheck_merge
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tree-wide pkgcheck error check
        uses: pkgcore/pkgcheck-action@v1
        with:
          args: --exit error -k error,-NonsolvableDepsInStable,-NonsolvableDepsInDev,-NonsolvableDepsInExp

      - name: Commit pkgcheck warnings
        uses: pkgcore/pkgcheck-action@v1
        with:
          args: --exit warning -k ,-NonsolvableDepsInStable,-NonsolvableDepsInDev,-PotentialStable --commits HEAD^..${{ github.sha }}
